//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pizzzUIMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemPrice
    {
        public int ID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ItemSize ItemSize { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
