//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngMap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pizzzaDatabaseEntities : DbContext
    {
        public pizzzaDatabaseEntities()
            : base("name=pizzzaDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ItemSize> ItemSizes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<MenuItemPrice> MenuItemPrices { get; set; }
        public virtual DbSet<PizzzaAdmin> PizzzaAdmins { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
